apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-downtime-blue
  labels:
    app: zero-downtime
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-downtime
      version: v1
  template:
    metadata:
      labels:
        app: zero-downtime
        version: v1
    spec:
      containers:
        - name: zero-downtime
          image: cryptic0053/zero-downtime:v1
          ports:
            - containerPort: 8000
