apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-downtime-green
  labels:
    app: zero-downtime
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-downtime
      version: v2
  template:
    metadata:
      labels:
        app: zero-downtime
        version: v2
    spec:
      containers:
        - name: zero-downtime
          image: cryptic0053/zero-downtime:v2
          ports:
            - containerPort: 8000
