apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-downtime
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: zero-downtime
  template:
    metadata:
      labels:
        app: zero-downtime
    spec:
      containers:
        - name: backend
          image: cryptic0053/zero-downtime-app:latest
          ports:
            - containerPort: 8000

