apiVersion: v1
kind: Service
metadata:
  name: zero-downtime-service
spec:
  selector:
    app: zero-downtime
    version: v1  # or v2 for green
  ports:
    - protocol: TCP
      port: 8000        # external port (NodePort target)
      targetPort: 8000  # port your Django app runs on
  type: NodePort
