apiVersion: v1
kind: Service
metadata:
  name: zero-downtime-service
spec:
  selector:
    app: zero-downtime
    version: v1   # switch this to v2 for green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
